language: php
warnings_are_errors: false

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: CS_FIXER=run

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit fabpot/php-cs-fixer --no-update
  - composer global update --prefer-dist --no-interaction
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - make test

after_success:
  - php vendor/bin/coveralls -c .coveralls.yml -v
